### ISSUE TITLE
Java or C++

### ISSUE THREAD

**Issue by imdreamrunner** [NTU-FSM/ACMaimeng-cheat-sheet#3]
Shall we change, or shall we stay?

**Comment by cly753** [comment]
shall we ... i don't know..

**Comment by imdreamrunner** [comment]
@lushl9301 any... er ...idea?

**Comment by lushl9301** [comment]
walao! can use @ !!!

**Comment by lushl9301** [comment]
it depends....

**Comment by imdreamrunner** [comment]
wooo depends on questions? that's reasonable. so we prepare both lol?

**Comment by lushl9301** [comment]
depends on user...

**Comment by imdreamrunner** [comment]
So the cheat sheet would be in what lang?

**Comment by cly753** [comment]
BigInteger is so good...

**Comment by imdreamrunner** [comment]
True Story. So focus on both lol,,

**Comment by lushl9301** [comment]
can have different version with different language.

**Comment by imdreamrunner** [comment]
手动点赞

**Comment by lushl9301** [comment]
yeah

**Comment by cly753** [comment]
liked
